spring:
  profiles:
    active: default
---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.67.148.118:3306/STUDY_TOGETHER?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username : root
    password : root123!new

  redis:
    host: localhost
    port: 6379

  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  logging:
    level:
      org:
        springframework:
          nodeValue: INFO
          web: DEBUG
      org.hibernate: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: studytogether756@gmail.com
    password: oqqd hqvo fgca owfn
    properties:
      mail.smtp.debug: true
      mail.smtp.connection-timeout: 1000
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    operations-sorter: method
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/STUDY_TOGETHER?useSSL=false&serverTimezone=UTC
    password: root
  sql:
    init:
      mode: always
        # data-locations: classpath:schema.sql

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  logging:
    level:
      org:
        springframework:
          nodeValue: INFO
          web: DEBUG
      org.hibernate: DEBUG
            # type: TRACE  # Hibernate의 TRACE 레벨 로그 활성화
            # orm.jdbc.bind: trace  # SQL 쿼리 로그를 위한 설정
            # type.descriptor.sql.BasicBinder: TRACE  # 바인딩된 SQL 파라미터 로그를 위한 설정

  mail:
    host: smtp.gmail.com
    port: 587
    username: studytogether756@gmail.com
    password: oqqd hqvo fgca owfn
    properties:
      mail.smtp.debug: true
      mail.smtp.connection-timeout: 1000
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect